### ISSUE TITLE
TypeError: int() argument must be a string, a bytes-like object or a number, not 'map'

### ISSUE THREAD

**Issue by saisivasriram** [priya-dwivedi/cs224n-Squad-Project#7]
Can any one help on this.. if u faced similar issue?? Got stucked for 2 days :(

Traceback (most recent call last):
  File "main.py", line 233, in <module>
    tf.app.run()
  File "C:\ProgramData\Anaconda3\lib\site-packages\tensorflow\python\platform\app.py", line 125, in run
    _sys.exit(main(argv))
  File "main.py", line 191, in main
    qa_model.train(sess, train_context_path, train_qn_path, train_ans_path, dev_qn_path, dev_context_path, dev_ans_path)
  File "D:\MOM\cs224n-Squad-Project-master\code\qa_model.py", line 855, in train
    loss, global_step, param_norm, grad_norm = self.run_train_iter(session, batch, summary_writer)
  File "D:\MOM\cs224n-Squad-Project-master\code\qa_model.py", line 449, in run_train_iter
    [_, summaries, loss, global_step, param_norm, gradient_norm] = session.run(output_feed, input_feed)
  File "C:\ProgramData\Anaconda3\lib\site-packages\tensorflow\python\client\session.py", line 900, in run
    run_metadata_ptr)
  File "C:\ProgramData\Anaconda3\lib\site-packages\tensorflow\python\client\session.py", line 1104, in _run
    np_val = np.asarray(subfeed_val, dtype=subfeed_dtype)
  File "C:\ProgramData\Anaconda3\lib\site-packages\numpy\core\numeric.py", line 492, in asarray
    return array(a, dtype, copy=False, order=order)
TypeError: int() argument must be a string, a bytes-like object or a number, not 'map'

**Comment by vanikanjirangat** [comment]
Hi,
Did you solve the issue. I am having the same problem.

**Comment by christinedifonzo12** [comment]
Did you figure out how to fix this?

**Comment by libertatis** [comment]
If you use Python3, the function 'map' returns a iterator, not a list. You should convert it to a list object manually, i.e., list(map(...)).
